artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/dataingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/dataingestion/data.zip
  unzip_dir: artifacts/dataingestion